
set background=light
set nocompatible
set encoding=utf-8
set nowrap
filetype off
syntax on

" mappings
" set the leader to space
let mapleader = " "
" toggle nerdtree via ctrl-n
map <C-n> :NERDTreeToggle<CR>
" toggle tagbar via ctrl-m
map <C-m> :TagbarToggle<CR>

" close buffer but not split window with ctrl-c
nnoremap <C-c> :bp\|bd #<CR>

" switch split windows with ctrl-j and ctrl-k
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-H> <C-WH>

" make backspace work like most other programs
set backspace=2

set guicursor+=n-v-c:blinkon0

"""""""""""""""""""""""""""""""""""""
" Configuration Section

"enable copying to clipboard
"set clipboard=unnamed

" show line numbers, show position, use mouse to scroll 
set number
set ruler
set mouse=a

" font
set antialias
set guifont=Inconsolata-dz-Powerline:h13


" Set Proper Tabs
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set autoindent

" Always display the status line
set laststatus=2

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'vim-syntastic/syntastic'

" automatically close parentheses
Plugin 'delimitMate.vim'

"ultisnips
" Track the engine.
Plugin 'SirVer/ultisnips'
" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" Plugin 'Valloric/YouCompleteMe'

call vundle#end()

" Colors
set background=light
colorscheme artesanal 
" YCM settings
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

"ultisnips settings
" Trigger configuration.
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" vim-airline configuration
let g:airline_powerline_fonts = 1 
let g:airline_theme='hybrid'
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1 

" Syntastic Configuration
let b:syntastic_mode = 'active'
let g:syntastic_check_on_open = 1
let g:syntastic_python_checkers = ['pyflakes']

"disable all style warnings in syntastic
"let g:syntastic_quiet_messages = { "type": "style" }

let g:syntastic_error_symbol = '✘'
let g:syntastic_warning_symbol = "▲"
